SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

DROP SCHEMA IF EXISTS `optimak_db`;
CREATE SCHEMA IF NOT EXISTS `optimak_db` DEFAULT CHARACTER SET utf8mb4;
USE `optimak_db`;


DROP TABLE IF EXISTS `EMPRESA`;

CREATE TABLE IF NOT EXISTS `EMPRESA` (
  `NIT`       CHAR(10)     NOT NULL,
  `Nombre`    VARCHAR(100) NOT NULL,
  `Direccion` VARCHAR(150) NOT NULL,
  `Ciudad`    VARCHAR(50)  NOT NULL,
  PRIMARY KEY (`NIT`),
  UNIQUE INDEX `NIT_UNIQUE` (`NIT` ASC)
) ENGINE = InnoDB;


DROP TABLE IF EXISTS `ADMINISTRADOR`;

CREATE TABLE IF NOT EXISTS `ADMINISTRADOR` (
  `idADMINISTRADOR` INT          NOT NULL AUTO_INCREMENT,
  `Nombre`          VARCHAR(80)  NOT NULL,
  `Departamento`    VARCHAR(50)  NOT NULL,
  `HashContrasena`  VARCHAR(250) NOT NULL,
  `EMPRESA_NIT`     CHAR(10)     NOT NULL,
  PRIMARY KEY (`idADMINISTRADOR`),
  INDEX `fk_ADMINISTRADOR_EMPRESA_idx` (`EMPRESA_NIT` ASC),
  CONSTRAINT `fk_ADMINISTRADOR_EMPRESA`
    FOREIGN KEY (`EMPRESA_NIT`)
    REFERENCES `EMPRESA` (`NIT`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
) ENGINE = InnoDB;


DROP TABLE IF EXISTS `MODULO_OPERATIVO`;

CREATE TABLE IF NOT EXISTS `MODULO_OPERATIVO` (
  `idMODULO_OPERATIVO` CHAR(2)  NOT NULL,
  `EMPRESA_NIT`        CHAR(10) NOT NULL,
  PRIMARY KEY (`idMODULO_OPERATIVO`, `EMPRESA_NIT`),
  INDEX `fk_MODULO_OPERATIVO_EMPRESA_idx` (`EMPRESA_NIT` ASC),
  CONSTRAINT `fk_MODULO_OPERATIVO_EMPRESA`
    FOREIGN KEY (`EMPRESA_NIT`)
    REFERENCES `EMPRESA` (`NIT`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
) ENGINE = InnoDB;


DROP TABLE IF EXISTS `JORNADA_MODULO`;

CREATE TABLE IF NOT EXISTS `JORNADA_MODULO` (
  `idJORNADA_MODULO`                    BIGINT  NOT NULL AUTO_INCREMENT,
  `Fecha`                               DATE    NOT NULL,
  `Hora_inicio`                         TIME    NOT NULL,
  `Hora_fin`                            TIME    NOT NULL,
  `EsDiaLaborable`                      TINYINT NOT NULL DEFAULT 1,
  `MODULO_OPERATIVO_idMODULO_OPERATIVO` CHAR(2)  NOT NULL,
  `MODULO_OPERATIVO_EMPRESA_NIT`        CHAR(10) NOT NULL,
  PRIMARY KEY (`idJORNADA_MODULO`),
  UNIQUE INDEX `uq_jornada_modulo_fecha`
    (`MODULO_OPERATIVO_idMODULO_OPERATIVO`, `MODULO_OPERATIVO_EMPRESA_NIT`, `Fecha`),
  INDEX `fk_JORNADA_MODULO_idx`
    (`MODULO_OPERATIVO_idMODULO_OPERATIVO`, `MODULO_OPERATIVO_EMPRESA_NIT`),
  CONSTRAINT `fk_JORNADA_MODULO`
    FOREIGN KEY (`MODULO_OPERATIVO_idMODULO_OPERATIVO`, `MODULO_OPERATIVO_EMPRESA_NIT`)
    REFERENCES `MODULO_OPERATIVO` (`idMODULO_OPERATIVO`, `EMPRESA_NIT`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `chk_Hora_jornada` CHECK (`Hora_fin` > `Hora_inicio`)
) ENGINE = InnoDB;


DROP TABLE IF EXISTS `PAUSA_MODULO`;

CREATE TABLE IF NOT EXISTS `PAUSA_MODULO` (
  `idPAUSA_MODULO`       BIGINT       NOT NULL AUTO_INCREMENT,
  `Tipo_pausa`           VARCHAR(40)  NOT NULL,
  `Hora_inicio_pausa`    TIME         NOT NULL,
  `Duracion_minutos`     INT          NOT NULL,
  `idJORNADA_MODULO`     BIGINT       NOT NULL,
  PRIMARY KEY (`idPAUSA_MODULO`),
  INDEX `fk_PAUSA_JORNADA_idx` (`idJORNADA_MODULO` ASC),
  CONSTRAINT `fk_PAUSA_JORNADA`
    FOREIGN KEY (`idJORNADA_MODULO`)
    REFERENCES `JORNADA_MODULO` (`idJORNADA_MODULO`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `chk_Duracion_pausa` CHECK (`Duracion_minutos` > 0)
) ENGINE = InnoDB;


DROP TABLE IF EXISTS `REFERENCIA`;

CREATE TABLE IF NOT EXISTS `REFERENCIA` (
  `ID_REF`          VARCHAR(15)  NOT NULL,
  `Tipo_Prenda`     VARCHAR(50)  NOT NULL,
  `Cliente`         VARCHAR(80)  NOT NULL,
  `Coleccion`       VARCHAR(60)  NULL,
  `Precio_unitario` DECIMAL(8,2) NOT NULL,
  PRIMARY KEY (`ID_REF`),
  UNIQUE INDEX `ID_REF_UNIQUE` (`ID_REF` ASC),
  CONSTRAINT `chk_Precio_unitario` CHECK (`Precio_unitario` > 0)
) ENGINE = InnoDB;


DROP TABLE IF EXISTS `OPERACION`;

CREATE TABLE IF NOT EXISTS `OPERACION` (
  `ID_operacionREF`   INT          NOT NULL AUTO_INCREMENT,
  `Nombre_corto`      VARCHAR(40)  NOT NULL,
  `Detalle`           VARCHAR(255) NOT NULL,
  `Maquina`           VARCHAR(60)  NOT NULL,
  `SAM_operacion`     DECIMAL(5,2) NOT NULL,
  `REFERENCIA_ID_REF` VARCHAR(15)  NOT NULL,
  PRIMARY KEY (`ID_operacionREF`),
  INDEX `fk_OPERACION_REFERENCIA_idx` (`REFERENCIA_ID_REF` ASC),
  CONSTRAINT `fk_OPERACION_REFERENCIA`
    FOREIGN KEY (`REFERENCIA_ID_REF`)
    REFERENCES `REFERENCIA` (`ID_REF`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `chk_SAM_operacion` CHECK (`SAM_operacion` > 0)
) ENGINE = InnoDB;


DROP TABLE IF EXISTS `LOTE`;

CREATE TABLE IF NOT EXISTS `LOTE` (
  `OM`                                  VARCHAR(20) NOT NULL,
  `numero_remision_entrada`             VARCHAR(30) NOT NULL,
  `OC`                                  VARCHAR(25) NULL,
  `Color`                               VARCHAR(30) NOT NULL,
  `Cant_XXL`                            INT         NULL DEFAULT 0,
  `Cant_XL`                             INT         NULL DEFAULT 0,
  `Cant_L`                              INT         NULL DEFAULT 0,
  `Cant_M`                              INT         NULL DEFAULT 0,
  `Cant_S`                              INT         NULL DEFAULT 0,
  `Cant_XS`                             INT         NULL DEFAULT 0,
  `Fecha_ingreso_planta`                DATE        NOT NULL,
  `MODULO_OPERATIVO_idMODULO_OPERATIVO` CHAR(2)     NOT NULL,
  `MODULO_OPERATIVO_EMPRESA_NIT`        CHAR(10)    NOT NULL,
  `REFERENCIA_ID_REF`                   VARCHAR(15) NOT NULL,
  PRIMARY KEY (`OM`),
  UNIQUE INDEX `OM_UNIQUE` (`OM` ASC),
  INDEX `fk_LOTE_MODULO_OPERATIVO_idx`
    (`MODULO_OPERATIVO_idMODULO_OPERATIVO`, `MODULO_OPERATIVO_EMPRESA_NIT`),
  INDEX `fk_LOTE_REFERENCIA_idx` (`REFERENCIA_ID_REF` ASC),
  CONSTRAINT `fk_LOTE_MODULO_OPERATIVO`
    FOREIGN KEY (`MODULO_OPERATIVO_idMODULO_OPERATIVO`, `MODULO_OPERATIVO_EMPRESA_NIT`)
    REFERENCES `MODULO_OPERATIVO` (`idMODULO_OPERATIVO`, `EMPRESA_NIT`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_LOTE_REFERENCIA`
    FOREIGN KEY (`REFERENCIA_ID_REF`)
    REFERENCES `REFERENCIA` (`ID_REF`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `chk_Cant_XXL` CHECK (`Cant_XXL` >= 0),
  CONSTRAINT `chk_Cant_XL`  CHECK (`Cant_XL`  >= 0),
  CONSTRAINT `chk_Cant_L`   CHECK (`Cant_L`   >= 0),
  CONSTRAINT `chk_Cant_M`   CHECK (`Cant_M`   >= 0),
  CONSTRAINT `chk_Cant_S`   CHECK (`Cant_S`   >= 0),
  CONSTRAINT `chk_Cant_XS`  CHECK (`Cant_XS`  >= 0)
) ENGINE = InnoDB;


DROP TABLE IF EXISTS `EMPLEADO_OPERATIVO`;

CREATE TABLE IF NOT EXISTS `EMPLEADO_OPERATIVO` (
  `Numero_cedula`                       VARCHAR(15)            NOT NULL,
  `Nombre`                              VARCHAR(80)            NOT NULL,
  `Telefono`                            VARCHAR(15)            NULL,
  `Edad`                                TINYINT                NOT NULL,
  `Sexo`                                ENUM('M', 'F', 'Otro') NOT NULL,
  `Cargo_rol`                           VARCHAR(40)            NOT NULL,
  `Correo`                              VARCHAR(100)           NULL,
  `HashContrasena`                      VARCHAR(250)           NOT NULL,
  `Activo`                              TINYINT                NOT NULL DEFAULT 1,
  `MODULO_OPERATIVO_idMODULO_OPERATIVO` CHAR(2)                NOT NULL,
  `MODULO_OPERATIVO_EMPRESA_NIT`        CHAR(10)               NOT NULL,
  PRIMARY KEY (`Numero_cedula`),
  UNIQUE INDEX `Numero_cedula_UNIQUE` (`Numero_cedula` ASC),
  UNIQUE INDEX `Correo_UNIQUE` (`Correo` ASC),
  INDEX `fk_EMPLEADO_MODULO_OPERATIVO_idx`
    (`MODULO_OPERATIVO_idMODULO_OPERATIVO`, `MODULO_OPERATIVO_EMPRESA_NIT`),
  CONSTRAINT `fk_EMPLEADO_MODULO_OPERATIVO`
    FOREIGN KEY (`MODULO_OPERATIVO_idMODULO_OPERATIVO`, `MODULO_OPERATIVO_EMPRESA_NIT`)
    REFERENCES `MODULO_OPERATIVO` (`idMODULO_OPERATIVO`, `EMPRESA_NIT`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `chk_Activo` CHECK (`Activo` IN (0, 1))
) ENGINE = InnoDB;


-- ------------------------------------------------------------
-- nueva tabla para lo del historial de asignacionnes
-- ------------------------------------------------------------
DROP TABLE IF EXISTS `HISTORIAL_MODULO_EMPLEADO`;

CREATE TABLE IF NOT EXISTS `HISTORIAL_MODULO_EMPLEADO` (
  `idHISTORIAL`                         BIGINT       NOT NULL AUTO_INCREMENT,
  `FechaInicio`                         DATE         NOT NULL,
  `FechaFin`                            DATE         NULL,
  `Numero_cedula`                       VARCHAR(15)  NOT NULL,
  `MODULO_OPERATIVO_idMODULO_OPERATIVO` CHAR(2)      NOT NULL,
  `MODULO_OPERATIVO_EMPRESA_NIT`        CHAR(10)     NOT NULL,
  PRIMARY KEY (`idHISTORIAL`),
  INDEX `fk_HISTORIAL_EMPLEADO_idx` (`Numero_cedula` ASC),
  INDEX `fk_HISTORIAL_MODULO_idx`
    (`MODULO_OPERATIVO_idMODULO_OPERATIVO`, `MODULO_OPERATIVO_EMPRESA_NIT`),
  CONSTRAINT `fk_HISTORIAL_EMPLEADO`
    FOREIGN KEY (`Numero_cedula`)
    REFERENCES `EMPLEADO_OPERATIVO` (`Numero_cedula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_HISTORIAL_MODULO`
    FOREIGN KEY (`MODULO_OPERATIVO_idMODULO_OPERATIVO`, `MODULO_OPERATIVO_EMPRESA_NIT`)
    REFERENCES `MODULO_OPERATIVO` (`idMODULO_OPERATIVO`, `EMPRESA_NIT`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `chk_Fechas_historial` CHECK (
    `FechaFin` IS NULL OR `FechaFin` >= `FechaInicio`
  )
) ENGINE = InnoDB;


DROP TABLE IF EXISTS `REGISTRO_PULSACION`;

CREATE TABLE IF NOT EXISTS `REGISTRO_PULSACION` (
  `ID_pulsacion`              BIGINT      NOT NULL AUTO_INCREMENT,
  `timestamp_pulsacion`       DATETIME    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `Numero_cedula`             VARCHAR(15) NOT NULL,
  `OPERACION_ID_operacionREF` INT         NOT NULL,
  `LOTE_OM`                   VARCHAR(20) NOT NULL,
  PRIMARY KEY (`ID_pulsacion`),
  INDEX `fk_PULSACION_EMPLEADO_idx` (`Numero_cedula` ASC),
  INDEX `fk_PULSACION_OPERACION_idx` (`OPERACION_ID_operacionREF` ASC),
  INDEX `fk_PULSACION_LOTE_idx` (`LOTE_OM` ASC),
  CONSTRAINT `fk_PULSACION_EMPLEADO`
    FOREIGN KEY (`Numero_cedula`)
    REFERENCES `EMPLEADO_OPERATIVO` (`Numero_cedula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PULSACION_OPERACION`
    FOREIGN KEY (`OPERACION_ID_operacionREF`)
    REFERENCES `OPERACION` (`ID_operacionREF`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PULSACION_LOTE`
    FOREIGN KEY (`LOTE_OM`)
    REFERENCES `LOTE` (`OM`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
) ENGINE = InnoDB;


DROP TABLE IF EXISTS `REGISTRO_EFICIENCIA`;

CREATE TABLE IF NOT EXISTS `REGISTRO_EFICIENCIA` (
  `idREGISTRO_EFICIENCIA` BIGINT       NOT NULL AUTO_INCREMENT,
  `Periodo_Inicio`        DATETIME     NOT NULL,
  `Periodo_Fin`           DATETIME     NOT NULL,
  `CantidadProducida`     INT          NOT NULL DEFAULT 0,
  `EficienciaPorcentaje`  DECIMAL(5,2) NOT NULL DEFAULT 0.00,
  `Observaciones`         VARCHAR(255) NULL,
  `Numero_cedula`         VARCHAR(15)  NOT NULL,
  `OM`                    VARCHAR(20)  NOT NULL,
  PRIMARY KEY (`idREGISTRO_EFICIENCIA`),
  INDEX `fk_EFICIENCIA_EMPLEADO_idx` (`Numero_cedula` ASC),
  INDEX `fk_EFICIENCIA_LOTE_idx` (`OM` ASC),
  CONSTRAINT `fk_EFICIENCIA_EMPLEADO`
    FOREIGN KEY (`Numero_cedula`)
    REFERENCES `EMPLEADO_OPERATIVO` (`Numero_cedula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_EFICIENCIA_LOTE`
    FOREIGN KEY (`OM`)
    REFERENCES `LOTE` (`OM`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `chk_Periodo` CHECK (`Periodo_Fin` > `Periodo_Inicio`),
  CONSTRAINT `chk_EficienciaPorcentaje` CHECK (`EficienciaPorcentaje` >= 0)
) ENGINE = InnoDB;


DROP TABLE IF EXISTS `INCIDENCIA`;

CREATE TABLE IF NOT EXISTS `INCIDENCIA` (
  `idINCIDENCIA`          BIGINT       NOT NULL AUTO_INCREMENT,
  `FechaHora`             DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `Descripcion`           VARCHAR(500) NOT NULL,
  `Numero_cedula`         VARCHAR(15)  NOT NULL,
  `idREGISTRO_EFICIENCIA` BIGINT       NOT NULL,
  PRIMARY KEY (`idINCIDENCIA`),
  INDEX `fk_INCIDENCIA_EMPLEADO_idx` (`Numero_cedula` ASC),
  INDEX `fk_INCIDENCIA_EFICIENCIA_idx` (`idREGISTRO_EFICIENCIA` ASC),
  CONSTRAINT `fk_INCIDENCIA_EMPLEADO`
    FOREIGN KEY (`Numero_cedula`)
    REFERENCES `EMPLEADO_OPERATIVO` (`Numero_cedula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_INCIDENCIA_EFICIENCIA`
    FOREIGN KEY (`idREGISTRO_EFICIENCIA`)
    REFERENCES `REGISTRO_EFICIENCIA` (`idREGISTRO_EFICIENCIA`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `chk_Descripcion` CHECK (CHAR_LENGTH(`Descripcion`) > 0)
) ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;